# Generated by Django 4.2.4 on 2023-08-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mode', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminModeData',
        ),
    ]
