# Generated by Django 4.2.4 on 2023-08-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adminmodedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminModeData',
        ),
    ]
