# Generated by Django 4.2.4 on 2023-08-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='default_post_image.jpg', null=True, upload_to='post_pics/'),
        ),
    ]
