# Generated by Django 4.2.4 on 2023-08-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_likes_alter_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_html',
            field=models.TextField(default='', editable=False),
        ),
    ]
