# Generated by Django 4.2.4 on 2023-08-24 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(choices=[('workouts', '운동'), ('diary', '다이어리'), ('travel', '여행'), ('uncategorized', '미분류')], on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blog.category'),
        ),
    ]
