# Generated by Django 4.2.4 on 2023-08-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_category_name_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('workouts', 'workouts'), ('diary', 'diary'), ('travel', 'travel'), ('uncategorized', 'uncategorized')], default='uncategorized', max_length=15),
        ),
    ]
