# Generated by Django 4.2.4 on 2023-08-24 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
