# Generated by Django 4.2.4 on 2023-08-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('diary', 'diary'), ('travel', 'travel'), ('workouts', 'workouts'), ('etc', 'etc')], default='uncategorized', max_length=15),
        ),
    ]
